### ISSUE TITLE
GraphQL course IDs should be strings not numbers

### ISSUE THREAD

**Issue by NEUDitao** [sandboxnu/course-catalog-api#2]
Currently, the `classID` field of a `Class` is a number. This causes id's with leading 0's such as "0045" to get truncated to "45." While this can be solved by using [leftPad](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/) or something, we should make a string to restore the leading 0's

**Comment by gamburgm** [comment]
Should be completed
